name       : telegram-qt
version    : 0.1.0
release    : 1
source     :
    - https://github.com/Kaffeine/telegram-qt/archive/telegram-qt-0.1.0.tar.gz : b0d6a88bdd0438657dbf737c7233f8b595e8cada495b60953e2ab4a46f406852
license    : LGPL-2.1
component  : programming.library
summary    : Telegram binding for Qt
description: |
    Telegram binding for Qt
builddeps  :
    - pkgconfig(Qt5Core)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
